/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as UsersRouteImport } from './routes/users'
import { Route as DebtorsIndexRouteImport } from './routes/debtors.index'
import { Route as DebtorsIdRouteImport } from './routes/debtors.$id'
import { Route as EmployeesIndexRouteImport } from './routes/employees.index'
import { Route as EmployeesIdRouteImport } from './routes/employees.$id'
import { Route as TerritoriesIndexRouteImport } from './routes/territories.index'
import { Route as TerritoriesIdRouteImport } from './routes/territories.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtorsIndexRoute = DebtorsIndexRouteImport.update({
  id: '/debtors/',
  path: '/debtors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtorsIdRoute = DebtorsIdRouteImport.update({
  id: '/debtors/$id',
  path: '/debtors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritoriesIndexRoute = TerritoriesIndexRouteImport.update({
  id: '/territories/',
  path: '/territories/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritoriesIdRoute = TerritoriesIdRouteImport.update({
  id: '/territories/$id',
  path: '/territories/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/debtors/$id': typeof DebtorsIdRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/territories/$id': typeof TerritoriesIdRoute
  '/debtors/': typeof DebtorsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/territories/': typeof TerritoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/debtors/$id': typeof DebtorsIdRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/territories/$id': typeof TerritoriesIdRoute
  '/debtors': typeof DebtorsIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/territories': typeof TerritoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/debtors/$id': typeof DebtorsIdRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/territories/$id': typeof TerritoriesIdRoute
  '/debtors/': typeof DebtorsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/territories/': typeof TerritoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/reports'
    | '/users'
    | '/debtors/$id'
    | '/employees/$id'
    | '/territories/$id'
    | '/debtors/'
    | '/employees/'
    | '/territories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/reports'
    | '/users'
    | '/debtors/$id'
    | '/employees/$id'
    | '/territories/$id'
    | '/debtors'
    | '/employees'
    | '/territories'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/reports'
    | '/users'
    | '/debtors/$id'
    | '/employees/$id'
    | '/territories/$id'
    | '/debtors/'
    | '/employees/'
    | '/territories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  ReportsRoute: typeof ReportsRoute
  UsersRoute: typeof UsersRoute
  DebtorsIdRoute: typeof DebtorsIdRoute
  EmployeesIdRoute: typeof EmployeesIdRoute
  TerritoriesIdRoute: typeof TerritoriesIdRoute
  DebtorsIndexRoute: typeof DebtorsIndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  TerritoriesIndexRoute: typeof TerritoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debtors/': {
      id: '/debtors/'
      path: '/debtors'
      fullPath: '/debtors/'
      preLoaderRoute: typeof DebtorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debtors/$id': {
      id: '/debtors/$id'
      path: '/debtors/$id'
      fullPath: '/debtors/$id'
      preLoaderRoute: typeof DebtorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$id': {
      id: '/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territories/': {
      id: '/territories/'
      path: '/territories'
      fullPath: '/territories/'
      preLoaderRoute: typeof TerritoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territories/$id': {
      id: '/territories/$id'
      path: '/territories/$id'
      fullPath: '/territories/$id'
      preLoaderRoute: typeof TerritoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  ReportsRoute: ReportsRoute,
  UsersRoute: UsersRoute,
  DebtorsIdRoute: DebtorsIdRoute,
  EmployeesIdRoute: EmployeesIdRoute,
  TerritoriesIdRoute: TerritoriesIdRoute,
  DebtorsIndexRoute: DebtorsIndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  TerritoriesIndexRoute: TerritoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
