/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebtorsIndexRouteImport } from './routes/debtors.index'
import { Route as DebtorsIdRouteImport } from './routes/debtors.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtorsIndexRoute = DebtorsIndexRouteImport.update({
  id: '/debtors/',
  path: '/debtors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtorsIdRoute = DebtorsIdRouteImport.update({
  id: '/debtors/$id',
  path: '/debtors/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debtors/$id': typeof DebtorsIdRoute
  '/debtors/': typeof DebtorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debtors/$id': typeof DebtorsIdRoute
  '/debtors': typeof DebtorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debtors/$id': typeof DebtorsIdRoute
  '/debtors/': typeof DebtorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/debtors/$id' | '/debtors/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/debtors/$id' | '/debtors'
  id: '__root__' | '/' | '/debtors/$id' | '/debtors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebtorsIdRoute: typeof DebtorsIdRoute
  DebtorsIndexRoute: typeof DebtorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debtors/': {
      id: '/debtors/'
      path: '/debtors'
      fullPath: '/debtors/'
      preLoaderRoute: typeof DebtorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debtors/$id': {
      id: '/debtors/$id'
      path: '/debtors/$id'
      fullPath: '/debtors/$id'
      preLoaderRoute: typeof DebtorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebtorsIdRoute: DebtorsIdRoute,
  DebtorsIndexRoute: DebtorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
