/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebtorsIndexRouteImport } from './routes/debtors.index'
import { Route as DebtorsIdRouteImport } from './routes/debtors.$id'
import { Route as EmployeesIndexRouteImport } from './routes/employees.index'
import { Route as TerritoriesIndexRouteImport } from './routes/territories.index'
import { Route as TerritoriesIdRouteImport } from './routes/territories.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtorsIndexRoute = DebtorsIndexRouteImport.update({
  id: '/debtors/',
  path: '/debtors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtorsIdRoute = DebtorsIdRouteImport.update({
  id: '/debtors/$id',
  path: '/debtors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritoriesIndexRoute = TerritoriesIndexRouteImport.update({
  id: '/territories/',
  path: '/territories/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritoriesIdRoute = TerritoriesIdRouteImport.update({
  id: '/territories/$id',
  path: '/territories/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debtors/$id': typeof DebtorsIdRoute
  '/territories/$id': typeof TerritoriesIdRoute
  '/debtors/': typeof DebtorsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/territories/': typeof TerritoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debtors/$id': typeof DebtorsIdRoute
  '/territories/$id': typeof TerritoriesIdRoute
  '/debtors': typeof DebtorsIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/territories': typeof TerritoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debtors/$id': typeof DebtorsIdRoute
  '/territories/$id': typeof TerritoriesIdRoute
  '/debtors/': typeof DebtorsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/territories/': typeof TerritoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debtors/$id'
    | '/territories/$id'
    | '/debtors/'
    | '/employees/'
    | '/territories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debtors/$id'
    | '/territories/$id'
    | '/debtors'
    | '/employees'
    | '/territories'
  id:
    | '__root__'
    | '/'
    | '/debtors/$id'
    | '/territories/$id'
    | '/debtors/'
    | '/employees/'
    | '/territories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebtorsIdRoute: typeof DebtorsIdRoute
  TerritoriesIdRoute: typeof TerritoriesIdRoute
  DebtorsIndexRoute: typeof DebtorsIndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  TerritoriesIndexRoute: typeof TerritoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debtors/': {
      id: '/debtors/'
      path: '/debtors'
      fullPath: '/debtors/'
      preLoaderRoute: typeof DebtorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debtors/$id': {
      id: '/debtors/$id'
      path: '/debtors/$id'
      fullPath: '/debtors/$id'
      preLoaderRoute: typeof DebtorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territories/': {
      id: '/territories/'
      path: '/territories'
      fullPath: '/territories/'
      preLoaderRoute: typeof TerritoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territories/$id': {
      id: '/territories/$id'
      path: '/territories/$id'
      fullPath: '/territories/$id'
      preLoaderRoute: typeof TerritoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebtorsIdRoute: DebtorsIdRoute,
  TerritoriesIdRoute: TerritoriesIdRoute,
  DebtorsIndexRoute: DebtorsIndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  TerritoriesIndexRoute: TerritoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
